# -*- coding: utf-8 -*-
"""internal_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-i7n7soGJgSTeldGN5cb57kjz20JdtlM

1.
"""

length=input()
width=input()
area= int(length) * int(width)
if area>2500:
  print("The area is large",area,"sqm")
elif area>1000 and area<2500:
  print("The area is medium",area,"sqm")
elif area<1000:
  print("The area is small",area,"sqm")

"""2."""

weight=input("Enter the weight in kg:")
height=input("Enter the height in m:")
weight1=float(weight)
heigh=float(height)
BMI = weight1/(heigh*heigh)
print(BMI)
if BMI<18:
  print("BMI is low:",BMI,"Take good food and work on exercise and yoga. Consult a dietician")
elif BMI>=18 and BMI<=24:
  print("BMI is good:",BMI,"Maintain the BMI with good diet and exercise")
elif BMI<24:
  print("BMI is high:",BMI,"Go and consult a doctor and work on the diet and exercise. else it will lead to obesity")

"""3."""

def report(sub_dic,stu_dic):
  for key, value in sub_dic.items():
    for key,value in stu_dic.items():

sub_dic={'English':'A','Maths':'A+','Science':'B','Lab':'B+'}
stu_dic={'amutha':'English','Kayal':'Maths','Mano':'Science','Manoj':'Lab'}
result=report(sub_dic,stu_dic)

"""4."""

age=input("Enter your age:")
recomend=input("Enter you recommendations for tv shows and movies:")
content_rating=input("content rating:")
int(age)
str(recomend)
int(content_rating)
if age<=10 and content_rating<3:
  print("You are a children and the TV shows and movies are shown")
elif age>10 and age<20 and content_rating<5:
  print("You are a teen and the TV shows and movies are shown")
elif age>=20 and age<=40 and content_rating<9:
  print("You are an adult person and the TV shows and movies are shown")
elif age>40 and content_rating>=9:
  print("You are a senior person and the TV shows and movies are shown")

"""5."""

sub_id=[1234,890,53,131,901]
result_list=[float]
for subid in sub_id:
  if subid%2==0:
    result_list.append(subid)
print(result_list)

"""6."""

password=1234
enter_pass=input("Enter your password:")
int_pass=int(enter_pass)
while 1:
  if password==int_pass:
    print("access allowed")
    break
  else:
    print("wrong password")
    input("Enter your password:")

"""7."""

def feedback(feeddback_list):
  result= sum(feedback_list)/len(feedback_list)
  return result
feedback_list=[6,9,9,6,7,5,4,3]
result=feedback(feedback_list)
print(result)
if result<=6:
  print("customers are not satisfied")
else:
  print("customers are satisfied")

"""8."""

def counting(my_input):
  result=0
  for i in range(0,len(my_input)):
    if my_input=='a'or my_input=='e' or my_input=='i' or my_input=='o'or my_input=='u':
      result= result+1
  return result
my_input=input("Enter your comments:")
my_input=my_input.lower()
result=counting(my_input)

"""9.

10.

11.
"""

Name=input("enter your name:")
Age=input("enter your age:")
Coming=input("are you coming?")

if type(Name)==str(Name):
  break
else:
  Name=input("enter your name:")
if type(Age)==int(Age):
  break
else:
  Age=input("enter your age:")
if type(Coming)==bool(Coming):
  break
else:
  Name=input("enter your name:")

"""12."""

n1=list(input("Enter your input list:"))
n2=list(input("Enter your input list:"))
addition=n1+n2
subraction=n1-n2
multiplication=n1*n2
if n2==0:
  division=n1
else:
  division=n1/n2
print(addition)
print(subraction)
print(multiplication)
print(division)

"""13."""