# -*- coding: utf-8 -*-
"""lvadsusr174_poovisha_sabapathi_KNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F-QzE5Qo3EDxmFjPVE89lo2RNPZzEDou
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings("ignore")

from sklearn.preprocessing import LabelEncoder,StandardScaler,PolynomialFeatures
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report

data=pd.read_csv('/content/winequality-red.csv')
df=pd.DataFrame(data)
df.head()

df.describe()

df.info()

df.isnull().sum()

df.duplicated().sum()

duplicated_rows = df[df.duplicated(keep=False)]
print(duplicated_rows)

df = df.drop_duplicates()

np.size(df)

np.shape(df)

df.duplicated().sum()

pd.isna(df['fixed acidity'])

df.dropna(how='any', axis=0,inplace = True)

df.isnull().sum()

numerical_cols=df.select_dtypes(include=['int64','float64'])
corr_mat=numerical_cols.corr()
plt.figure(figsize=(15,7))
sns.heatmap(corr_mat,annot=True)

X=df.drop(columns=['quality'])
y=df['quality'].values

model =  KNeighborsClassifier(n_neighbors=2)
model.fit(X, y)

y_predict = model.predict(X)
print(y_predict)
model_predictions = [round(value) for value in y_predict]

accuracy = accuracy_score(y,model_predictions)
print("Model Prediction Accuracy: %.2f%%" % (accuracy * 100.0))