# -*- coding: utf-8 -*-
"""lvadsusr174_poovisha_sabapathi_kmeans.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i8MuC89f6JtGNxauAzvZvWyL7eejHGVH
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings("ignore")

from sklearn.preprocessing import LabelEncoder,StandardScaler,PolynomialFeatures
from sklearn.model_selection import train_test_split
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

df=pd.read_csv('/content/customer_segmentation.csv')
df.head()

df.info()

df.isnull().sum()

null_rows = df[df.isnull().any(axis=1)]
null_rows

for column in df.select_dtypes(include=['float64', 'int64']).columns:
    plt.figure(figsize=(10, 5))
    sns.histplot(df[column])
    plt.title(f'Histogram of {column}')
    plt.xlabel(column)
    plt.ylabel('Frequency')
    plt.show()

for column in df.select_dtypes(include=['object']).columns:
  plt.figure(figsize=(15,5))
  df[column].value_counts().plot(kind='bar')
  plt.xticks(rotation=45)
  plt.title(f'Bar plot of {column}')
  plt.xlabel(column)
  plt.ylabel('Frequency')
  plt.show()

df=df.fillna(df['Income'].median())

df.isnull().sum()

df.duplicated().sum()

numerical_cols=df.select_dtypes(include=['int64','float64'])
corr_mat=numerical_cols.corr()
plt.figure(figsize=(20,7))
sns.heatmap(corr_mat,annot=True,cmap='coolwarm')

for column in df.select_dtypes(include=['float64','int64']):
  plt.figure(figsize=(20,10))
  sns.boxplot(df[[column]])

for column in df.select_dtypes(include = "number"):
  q1 = df[column].quantile(0.25)
  q3 = df[column].quantile(0.75)
  iqr = q3-q1
  lower = q1 - 1.5*iqr
  upper = q3 + 1.5* iqr
  df[column] = df[column].clip(lower = lower, upper= upper)

for column in df.select_dtypes(include=['float64','int64']):
  plt.figure(figsize=(20,10))
  sns.boxplot(df[[column]])

def object_to_int(x):
  if x.dtype=='object':
    x=LabelEncoder().fit_transform(x)
  return x

df=df.apply(lambda x: object_to_int(x))
df.head(20)

df

km = KMeans(n_clusters=3)
y_pred = km.fit_predict(df[[column]])

df['cluster'] = y_pred

df1 = df[df.cluster == 0]
df2 = df[df.cluster == 1]
df3 = df[df.cluster == 2]


plt.scatter(df1.Dt_Customer,df1['NumStorePurchases'],color='hotpink')
plt.scatter(df2.Dt_Customer,df2['NumStorePurchases'],color='orange')
plt.scatter(df3.Dt_Customer,df3['NumStorePurchases'],color='red')

plt.scatter(km.cluster_centers_[:,0],km.cluster_centers_[:,1],color='green',marker='*',label='centroid')
plt.xlabel('Dt_Customer')
plt.ylabel('NumStorePurchases')
plt.legend()

silhouette_score(df, y_pred)

k_range = range(1,10)
sse = []
for k in k_range:
  km = KMeans(n_clusters=k)
  km.fit(df[['Dt_Customer','NumStorePurchases']])
  sse.append(km.inertia_)

plt.xlabel('Clusters')
plt.ylabel('SSE value')
plt.plot(k_range,sse,marker='.')